project:
  type: website
  output-dir: docs

website:
  title: "AMSA 2026-2027"
  favicon: "favicon.ico"
  navbar:
    left:
      - text: "🎓 Slides"
        menu:
        - href: weeks/week-0.qmd
          text: "Week 0"
        # - href: weeks/week-1.qmd
        #   text: "Week 1"
        # - href: weeks/week-2.qmd
        #   text: "Week 2"
        # - href: weeks/week-3.qmd
        #   text: "Week 3"
        # - href: weeks/week-4.qmd
        #   text: "Week 4"
        # - href: weeks/week-5.qmd
        #   text: "Week 5"
        # - href: weeks/week-6.qmd
        #   text: "Week 6"
        # - href: weeks/week-7.qmd
        #   text: "Week 7"
        # - href: weeks/week-9.qmd
        #   text: "Week 9"
        # - href: weeks/week-10.qmd
        #   text: "Week 10"
        # - href: weeks/week-11.qmd
        #   text: "Week 11"
        # - href: weeks/week-12.qmd
        #   text: "Week 12"
        # - href: weeks/week-13.qmd
        #   text: "Week 13"

      - text: "📚 Activities"
        # menu:
        # - href: activities/act-1.qmd
        #   text: "Activity 1"
        # - href: activities/act-2.qmd
        #   text: "Activity 2"
        # - href: activities/act-3.qmd
        #   text: "Activity 3"
        # - href: activities/act-4.qmd
        #   text: "Activity 4"
      - text: "🤓 Extras"
        # menu:
        # - href: weeks/week-1.qmd#extra
        #   text: "Week 1"
        # - href: weeks/week-2.qmd#extra
        #   text: "Week 2"
        # - href: weeks/week-3.qmd#extra
        #   text: "Week 3"
        # - href: weeks/week-4.qmd#extra
        #   text: "Week 4"
        # - href: weeks/week-5.qmd#extra
        #   text: "Week 5"
        # - href: weeks/week-6.qmd#extra
        #   text: "Week 6"
        # - href: weeks/week-7.qmd#extra
        #   text: "Week 7"
        # - href: weeks/week-9.qmd#extra
        #   text: "Week 9"
        # - href: weeks/week-10.qmd#extra
        #   text: "Week 10"
        # - href: weeks/week-11.qmd#extra
        #   text: "Week 11"
        # - href: weeks/week-12.qmd#extra
        #   text: "Week 12"
        # - href: weeks/week-13.qmd#extra
        #   text: "Week 13"

title: "AMSA"

author:
  - name: Ferran Aran Domingo
    email: ferran.aran@udl.cat
  - name: Oriol Agost Batalla
    email: oriol.agost@udl.cat
  - name: Pablo Fraile Alonso
    email: pablo.fraile@udl.cat

format:
  revealjs:
    theme: simple
    slide-number: true
    incremental: true 
    transition: fade
    toc: true
    toc-depth: 1
    chalkboard: true
  html:
    theme: lux
    css: styles.css
    toc: true
    link-external-newwindow: true
  pdf: default


editor: visual

execute:
  freeze: auto
  echo: true

mermaid:
      theme: neutral

logo: "logo.png"

footer: AMSA 2026-2027  -  [🏠 Home](/index.html)
